name: Bazel Test

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  check-commit:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check.outputs.skip }}
    steps:
      - name: Check for --no-test in commit message
        id: check
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"--no-test"* ]]; then
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

  bazel-test:
    needs: check-commit
    if: needs.check-commit.outputs.skip == 'false'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup bazel
        uses: jwlawson/actions-setup-bazel@v2
        with:
          bazel-version: '7.4.0'

      - name: Run Bazel build and tests
        working-directory: app
        run: |
          bazel build //:BazelProject --java_language_version=8 
          bazel test //:BazelProjectTest1 --java_language_version=8 
          bazel test //:BazelProjectTest2 --java_language_version=8
