name: Conditional Pipeline (Manual Git Diff)

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  precheck:
    runs-on: ubuntu-latest
    outputs:
      skip-pipeline: ${{ steps.check.outputs.skip }}
      src-changed: ${{ steps.diff.outputs.src_changed }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check for --no-pipeline in commit message
        id: check
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"--no-pipeline"* ]]; then
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Clone GuillaumeFalourd/poc-github-actions repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          repository: 'CICD-Performance-Patterns'
          owner: 'franz-program'
          branch: ${{ github.ref_name }}
          depth: 2
    
      - name: Detect changes in app/src
        working-directory: ./poc-github-actions
        id: diff
        run: |
            echo "Comparing commits:"
            echo "Before: ${{ github.event.before }}"
            echo "After:  ${{ github.sha }}"
    
            changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
            echo "$changed_files"
    
            if echo "$changed_files" | grep -q '^app/src/'; then
              echo "src_changed=true" >> $GITHUB_OUTPUT
            else
              echo "src_changed=false" >> $GITHUB_OUTPUT
            fi
        

  build:
    needs: precheck
    if: needs.precheck.outputs.skip-pipeline == 'false' && needs.precheck.outputs.src-changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building project..."

  test:
    needs: precheck
    if: needs.precheck.outputs.skip-pipeline == 'false' && (
          needs.precheck.outputs.src-changed == 'true' || github.ref == 'refs/heads/fake-branch'
        )
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running tests..."

  deploy:
    needs: [precheck, test]
    if: needs.precheck.outputs.skip-pipeline == 'false' && github.ref == 'refs/heads/fake-branch'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying..."
