name: Gradle Build with Cache

on:
  push:
 
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '--no-test')"
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Restore Gradle and build caches
        uses: actions/cache@v4
        with:
          path: |
            app/.gradle
            app/build
          key: gradle-cache-${{ github.ref_name }}

      - name: Gradle build with cache
        run: |
          ./gradlew clean build --build-cache