name: Conditional Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  skip-check:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check.outputs.skip }}
    steps:
      - name: Check commit message for --no-pipeline
        id: check
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"--no-pipeline"* ]]; then
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

  build:
    needs: skip-check
    if: needs.skip-check.outputs.skip == 'false'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Detect file changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            src:
              - 'app/src/**/*'

      - name: Build project
        if: steps.changes.outputs.src == 'true'
        run: echo "Building project..."

  test:
    needs: skip-check
    if: needs.skip-check.outputs.skip == 'false'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Detect file changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            src:
              - 'app/src/**/*'

      - name: Run tests
        # OR condition: changes OR correct branch
        if: steps.changes.outputs.src == 'true' || github.ref == 'refs/heads/fake-branch'
        run: echo "Running tests..."

  deploy:
    needs: [skip-check, test]
    if: needs.skip-check.outputs.skip == 'false' && github.ref == 'refs/heads/fake-branch'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying..."
