name: Conditional Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  check-conditions:
    runs-on: ubuntu-latest
    outputs:
      skip-pipeline: ${{ steps.check.outputs.skip }}
      src-changed: ${{ steps.filter.outputs.src }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for --no-pipeline in commit message
        id: check
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"--no-pipeline"* ]]; then
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Detect file changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            src:
              - 'app/src/**/*'

  build:
    needs: check-conditions
    if: needs.check-conditions.outputs.skip-pipeline == 'false' && needs.check-conditions.outputs.src-changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building project..."


  test:
    needs: check-conditions
    if: needs.check-conditions.outputs.skip-pipeline == 'false' && (
          needs.check-conditions.outputs.src-changed == 'true' || github.ref == 'refs/heads/conditional-triggering-main'
        )
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running tests..."

  deploy:
    needs: [check-conditions, test]
    if: needs.check-conditions.outputs.skip-pipeline == 'false' && github.ref == 'refs/heads/conditional-triggering-main'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying..."
