name: Bazel Tests in Docker (with Cache)

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  check-commit:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check.outputs.skip }}
    steps:
      - name: Check for --no-test in commit message
        id: check
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"--no-test"* ]]; then
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

  bazel-test:
    needs: check-commit
    if: needs.check-commit.outputs.skip == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore Bazel cache
        uses: actions/cache@v4
        with:
          path: app/testcache
          key: bazel-tutorial-cache
      
      - name: Prepare Bazel cache folder
        run: |
            mkdir -p bazel-cache
            chmod -R 777 bazel-cache

      - name: Bazel build
        run: |
            docker run --rm \
              -v "${{ github.workspace }}/app":/app \
              -w /app \
              gcr.io/bazel-public/bazel:7.4.0 \
              build //:BazelProject --java_language_version=8 --disk_cache=testcache
        
      - name: Bazel test 1
        run: |
            docker run --rm \
              -v "${{ github.workspace }}/app":/app \
              -w /app \
              gcr.io/bazel-public/bazel:7.4.0 \
              test //:BazelProjectTest1 --java_language_version=8 --disk_cache=testcache
        
      - name: Bazel test 2
        run: |
            docker run --rm \
              -v "${{ github.workspace }}/app":/app \
              -w /app \
              gcr.io/bazel-public/bazel:7.4.0 \
              test //:BazelProjectTest2 --java_language_version=8 --disk_cache=testcache